#ifndef VALORES_INICIALES_H
#define VALORES_INICIALES_H

#define CONTROL_VELKP 1
#define CONTROL_VELKI 10
#define CONTROL_VELKD 100

#define CONTROL_POSKP 2
#define CONTROL_POSKI 20
#define CONTROL_POSKD 200

#define POS_MIN -180
#define POS_MAX 180

#define VEL_MIN -45
#define VEL_MAX 45

#define MODO_CONTROL_VEL 1
#define MODO_CONTROL_POS 0

#define Tms 200 //en ms



#endif // VALORES_INICIALES_H

